//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurements
    {
        public int id { get; set; }
        public int host_id { get; set; }
        public byte[] timestamp { get; set; }
        public short load_cpu { get; set; }
        public short load_mem { get; set; }
    
        public virtual hosts hosts { get; set; }
    }
}
