//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.views = new HashSet<views>();
        }
       
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public short superuser { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<views> views { get; set; }
    }
}
