//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class views
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string type { get; set; }
        public string view_query { get; set; }
        public string status { get; set; }
    
        public virtual users users { get; set; }
    }
}
